# Generated by Django 4.1.7 on 2023-03-18 07:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quiz',
            name='points',
            field=models.IntegerField(default=0, verbose_name='Количество баллов'),
        ),
    ]
