# Generated by Django 4.1.7 on 2023-03-19 00:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0002_alter_quiz_points'),
    ]

    operations = [
        migrations.CreateModel(
            name='Alltask',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quize', models.CharField(blank=True, max_length=21, null=True, verbose_name='поле')),
            ],
        ),
        migrations.AlterModelOptions(
            name='geographic_features',
            options={'verbose_name': 'географический объект', 'verbose_name_plural': 'географические объекты'},
        ),
        migrations.RemoveField(
            model_name='geographic_features',
            name='max_points',
        ),
        migrations.RemoveField(
            model_name='geographic_features',
            name='question',
        ),
        migrations.RemoveField(
            model_name='geographic_features',
            name='quiz',
        ),
        migrations.AlterField(
            model_name='geographic_features',
            name='coordinates_dolg',
            field=models.CharField(max_length=50, verbose_name='Координаты долготы'),
        ),
        migrations.AlterField(
            model_name='geographic_features',
            name='coordinates_shir',
            field=models.CharField(max_length=50, verbose_name='Координаты широты'),
        ),
        migrations.CreateModel(
            name='Task3',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('task', models.CharField(max_length=300, verbose_name='Указать точку наиболее блюзкую к объекту')),
                ('coordinates', models.CharField(max_length=300, verbose_name='Ответ пользователя')),
                ('max_points', models.IntegerField(default=0, verbose_name='максимальное количство баллов')),
                ('Features', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shop.geographic_features', verbose_name='Географический обЪект')),
                ('altask', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='shop.alltask')),
            ],
        ),
        migrations.CreateModel(
            name='Task2',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('task', models.CharField(max_length=300, verbose_name='Указать точку наиболее блюзкую к объекту')),
                ('coordinates_shir', models.IntegerField(verbose_name='Координаты пользователя')),
                ('coordinates_dol', models.IntegerField(verbose_name='Координаты пользователя')),
                ('max_points', models.IntegerField(default=0, verbose_name='максимальное количство баллов')),
                ('Features', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shop.geographic_features', verbose_name='Географический обЪект')),
                ('altask', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='shop.alltask')),
            ],
        ),
        migrations.CreateModel(
            name='Task1',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('task', models.CharField(max_length=300, verbose_name='Выберите правильный географический объект')),
                ('tryy', models.IntegerField(verbose_name='Число попыток')),
                ('coordinates_shir', models.IntegerField(verbose_name='Координаты пользователя')),
                ('coordinates_dol', models.IntegerField(verbose_name='Координаты пользователя')),
                ('max_points', models.IntegerField(default=0, verbose_name='максимальное количство баллов')),
                ('Features', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shop.geographic_features', verbose_name='Географический обЪект')),
                ('altask', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='shop.alltask')),
            ],
        ),
        migrations.AddField(
            model_name='quiz',
            name='question',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='shop.alltask'),
        ),
    ]
