# Generated by Django 4.1.7 on 2023-03-19 10:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0004_remove_quiz_question_remove_task1_altask_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='quiz',
            old_name='User',
            new_name='user',
        ),
    ]
